FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma/
COPY tsconfig.json ./
COPY src ./src/

ENV DATABASE_URL="mysql://root:root@host.docker.internal:3306/hashmicro_hiring_test"
ENV PORT=8081

EXPOSE 8081

CMD ["npx", "ts-node-dev", "--respawn", "src/main.ts"]
